repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--enable-rule=terraform_documented_variables
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--skip-check CKV_TF_1
          - --args=--skip-check CKV_GCP_114
          - --args=--skip-check CKV_GCP_62
          - --args=--skip-check CKV_GCP_78
          - --args=--skip-check CKV_GCP_32
          - --args=--skip-check CKV_GCP_38
          - --args=--skip-check CKV_GCP_40
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: pretty-format-json
        args: [--autofix]
      - id: sort-simple-yaml
      - id: trailing-whitespace
